import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: [
      'tests/aiConfig.test.ts',
      'tests/aiProviderSecurity.test.ts',
      'tests/aiKeyWriteOnlyPolicy.test.ts',
      'tests/manageAiKeyHandler.test.ts',
      'tests/mutatingIntegrationSafety.test.ts',
      'tests/edgeHttp.test.ts',
      'tests/uiContracts.test.ts',
      'tests/navigation.test.ts',
      'tests/authStorage.test.ts',
      'tests/authStore.test.ts',
      'tests/questions.test.ts',
      'tests/practiceRestoration.test.ts',
      'tests/practiceStoreIsolation.test.ts',
      'tests/legacyScoringApi.test.ts',
      'tests/legacyScoringCore.test.ts',
      'tests/legacyScoringEdge.test.ts',
      'tests/legacyScoringPolicy.test.ts',
      'tests/questionValidation.test.ts',
      'tests/questionCsv.test.ts',
      'tests/questionApi.test.ts',
      'tests/questionApiPolicy.test.ts',
      'tests/questionImportPolicy.test.ts',
      'tests/questionImportValidation.test.ts',
      'tests/medInterviewQuestionBankImport.test.ts',
      'tests/candidateMmiImportPolicy.test.ts',
      'tests/candidateMmiApi.test.ts',
      'tests/candidateMmiScoring.test.ts',
      'tests/candidateMmiSpeech.test.ts',
      'tests/candidateMmiUiContract.test.ts',
      'tests/cofounderFeedback.test.ts',
      'tests/cofounderFeedbackPolicy.test.ts',
      'tests/cofounderHostedReconciliationPolicy.test.ts',
      'tests/cofounderPrivilegeCutoverPolicy.test.ts',
      'tests/hostedCatalogSnapshotPolicy.test.ts',
      'tests/releaseUiPolicy.test.ts',
    ],
    coverage: {
      provider: 'v8',
      include: [
        'supabase/functions/_shared/**/*.ts',
        'supabase/functions/manage-ai-key/handler.ts',
        'src/theme/designTokens.ts',
        'src/navigation/tabConfig.ts',
        'src/lib/navigation.ts',
        'src/lib/authStorageCore.ts',
        'src/stores/authStore.ts',
        'src/features/questions/selection.ts',
        'src/features/practice/restoration.ts',
        'src/features/practice/scoringApi.ts',
        'src/features/questions/validation.ts',
        'src/features/questions/importValidation.ts',
        'src/features/questions/csv.ts',
        'src/features/questions/api.ts',
        'src/features/candidateMmi/api.ts',
        'src/features/candidateMmi/featureFlag.ts',
        'src/features/candidateMmi/runner.ts',
        'src/features/candidateMmi/scoringApi.ts',
        'supabase/functions/score-candidate-mmi-response/handler.ts',
        'src/features/cofounderFeedback/api.ts',
      ],
      exclude: [
        'supabase/functions/_shared/mmiContracts.ts',
        'supabase/functions/_shared/mmiScoringContract.ts',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
  },
});
