import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '../../src/components/ui/Button';
import { FloatingInput as Input } from '../../src/components/ui/Input';
import { InlineNotice } from '../../src/components/feedback/InlineNotice';
import { createAdminMmiApi } from '../../src/features/adminMmi/api';
import type { AdminMmiAssessmentPurpose, AdminMmiAssessmentSummary } from '../../src/features/adminMmi/types';
import { navigateBackOr } from '../../src/lib/navigation';
import { supabase } from '../../src/lib/supabase';
import { colors, layout, text } from '../../src/theme';

const api = createAdminMmiApi(supabase);
const purposes: readonly AdminMmiAssessmentPurpose[] = ['scoring_review', 'support', 'cost_review', 'quality_audit'];
export default function AssessmentsScreen() {
  const [items, setItems] = useState<readonly AdminMmiAssessmentSummary[]>([]); const [loading, setLoading] = useState(true); const [userId, setUserId] = useState(''); const [stationId, setStationId] = useState(''); const [selected, setSelected] = useState<AdminMmiAssessmentSummary | null>(null); const [error, setError] = useState(false);
  const load = () => { setLoading(true); setError(false); void api.listAssessments({ limit: 50, offset: 0, userId: userId || undefined, stationId: stationId || undefined }).then((result) => setItems(result.items)).catch(() => setError(true)).finally(() => setLoading(false)); }; useEffect(load, []);
  return <SafeAreaView style={styles.safe}><View style={styles.header}><TouchableOpacity onPress={() => navigateBackOr(router, '/admin')} accessibilityRole="button"><Text style={styles.back}>Back to admin</Text></TouchableOpacity><Text style={styles.headerTitle}>ASSESSMENT EXPLORER</Text><View style={{ width: 104 }} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Assessment explorer</Text><Text style={styles.sub}>Open a structured rubric result only for a declared operational purpose. Detail access is audited and never includes candidate answer content.</Text>{error ? <InlineNotice title="Assessments not loaded" message="Check filters and administrator access." tone="error" /> : null}<Input label="User ID" value={userId} onChangeText={setUserId} autoCapitalize="none" /><Input label="Station ID" value={stationId} onChangeText={setStationId} autoCapitalize="none" /><Button label="Apply assessment filters" onPress={load} small />{loading ? <ActivityIndicator color={colors.teal[400]} style={{ margin: 30 }} /> : items.map((item) => <TouchableOpacity key={item.responseId} onPress={() => setSelected(item)} accessibilityRole="button"><View style={styles.row}><Text style={styles.rowTitle}>{item.userDisplayName} · {item.stationId} · Question {item.promptOrder}</Text><Text style={styles.meta}>{item.questionScorePct}% · {item.provider ?? 'No provider'} / {item.model ?? 'No model'} · {item.costKnown ? `$${item.estimatedCost}` : 'Cost unavailable'}</Text></View></TouchableOpacity>)}</ScrollView><Modal visible={selected !== null} transparent animationType="fade" onRequestClose={() => setSelected(null)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>Why are you opening this result?</Text><Text style={styles.modalCopy}>Choose one purpose. This creates an audit record before structured detail is returned.</Text>{purposes.map((purpose) => <Button key={purpose} label={purpose.replace('_', ' ')} variant="secondary" onPress={() => selected && router.push({ pathname: '/admin/assessment', params: { responseId: selected.responseId, purpose } })} style={{ marginTop: 8 }} />)}<Button label="Cancel" variant="danger" onPress={() => setSelected(null)} style={{ marginTop: 8 }} /></View></View></Modal></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg.primary }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 12, paddingHorizontal: layout.screenPaddingH, borderBottomWidth: 1, borderBottomColor: colors.primary[800] }, back: { ...text.labelMd, color: colors.primary[800], minWidth: 104 }, headerTitle: { ...text.labelMd, color: colors.primary[800] }, content: { padding: layout.screenPaddingH, paddingBottom: 48, gap: 10 }, title: { ...text.displayLg, color: colors.primary[800] }, sub: { ...text.bodyMd, color: colors.neutral[600], lineHeight: 22 }, row: { backgroundColor: colors.bg.white, borderWidth: 1, borderColor: colors.primary[300], padding: 13 }, rowTitle: { ...text.headingSm, color: colors.primary[800] }, meta: { ...text.bodySm, color: colors.neutral[600], marginTop: 4 }, overlay: { flex: 1, padding: 22, justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.45)' }, modal: { backgroundColor: colors.bg.white, borderWidth: 2, borderColor: colors.primary[800], padding: 20 }, modalTitle: { ...text.headingLg, color: colors.primary[800] }, modalCopy: { ...text.bodyMd, color: colors.neutral[600], marginTop: 8 } });
