import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '../../src/components/ui/Button';
import { FloatingInput as Input } from '../../src/components/ui/Input';
import { InlineNotice } from '../../src/components/feedback/InlineNotice';
import { createAdminMmiApi } from '../../src/features/adminMmi/api';
import type { AdminMmiContentStatus, AdminMmiDifficulty, AdminMmiStationSummary } from '../../src/features/adminMmi/types';
import { navigateBackOr } from '../../src/lib/navigation';
import { supabase } from '../../src/lib/supabase';
import { colors, layout, text } from '../../src/theme';

const api = createAdminMmiApi(supabase);
export default function StationsScreen() {
  const [items, setItems] = useState<readonly AdminMmiStationSummary[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [university, setUniversity] = useState(''); const [status, setStatus] = useState<AdminMmiContentStatus | undefined>(); const [category, setCategory] = useState(''); const [topic, setTopic] = useState(''); const [difficulty, setDifficulty] = useState(''); const [offset, setOffset] = useState(0); const [total, setTotal] = useState(0); const [error, setError] = useState(false);
  const load = () => { setLoading(true); setError(false); void api.listStations({ query, university, status, category, topic, difficulty: difficulty ? difficulty as AdminMmiDifficulty : undefined, limit: 25, offset }).then((result) => { setItems(result.items); setTotal(result.total); }).catch(() => setError(true)).finally(() => setLoading(false)); };
  useEffect(load, [offset, status]);
  return <SafeAreaView style={styles.safe}><View style={styles.header}><TouchableOpacity onPress={() => navigateBackOr(router, '/admin')} accessibilityRole="button"><Text style={styles.back}>Back to admin</Text></TouchableOpacity><Text style={styles.headerTitle}>STATION REPOSITORY</Text><View style={{ width: 104 }} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Station repository</Text><Text style={styles.sub}>A station is valid for candidate practice only when it has one scenario, five 120-second questions, and ordered marking criteria.</Text>{error ? <InlineNotice title="Stations not loaded" message="Check administrator access and retry." tone="error" /> : null}<Input label="Search station ID or content" value={query} onChangeText={setQuery} /><Input label="University tag" value={university} onChangeText={setUniversity} autoCapitalize="none" /><View style={styles.filterRow}>{(['draft', 'published', 'archived'] as const).map((value) => <TouchableOpacity key={value} onPress={() => setStatus(status === value ? undefined : value)} style={[styles.filter, status === value && styles.selected]} accessibilityRole="checkbox" accessibilityState={{ checked: status === value }}><Text style={styles.filterText}>{value}</Text></TouchableOpacity>)}</View><Input label="Category filter" value={category} onChangeText={setCategory} /><Input label="Topic filter" value={topic} onChangeText={setTopic} /><Input label="Difficulty filter" value={difficulty} onChangeText={setDifficulty} autoCapitalize="none" /><Button label="Apply repository filters" onPress={() => { setOffset(0); load(); }} small />{loading ? <ActivityIndicator color={colors.teal[400]} style={{ margin: 28 }} /> : items.map((item) => <View key={item.stationId} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.stationId}>{item.stationId} · v{item.contentVersion}</Text><Text style={styles.meta}>{item.category} · {item.topic} · {item.difficulty} · {item.status}</Text><Text style={styles.meta}>{item.universityTags.join(', ') || 'No university tags'} · {item.questionCount}/5 questions · {item.criterionCount} criteria · {item.isComplete ? 'complete' : 'incomplete'}</Text></View><Button label="Edit" small variant="secondary" onPress={() => router.push({ pathname: '/admin/station-editor', params: { stationId: item.stationId } })} /></View>)}{!loading && !items.length ? <Text style={styles.empty}>No matching stations on this page.</Text> : null}<View style={styles.pager}><Button label="Previous" small variant="secondary" disabled={offset === 0} onPress={() => setOffset(Math.max(0, offset - 25))} /><Text style={styles.meta}>{offset + 1}–{Math.min(offset + 25, total)} of {total}</Text><Button label="Next" small variant="secondary" disabled={offset + 25 >= total} onPress={() => setOffset(offset + 25)} /></View><Button label="Create station draft" onPress={() => router.push('/admin/station-editor')} /></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg.primary }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 12, paddingHorizontal: layout.screenPaddingH, borderBottomWidth: 1, borderBottomColor: colors.primary[800] }, back: { ...text.labelMd, color: colors.primary[800], minWidth: 104 }, headerTitle: { ...text.labelMd, color: colors.primary[800] }, content: { padding: layout.screenPaddingH, paddingBottom: 48, gap: 10 }, title: { ...text.displayLg, color: colors.primary[800] }, sub: { ...text.bodyMd, color: colors.neutral[500], lineHeight: 22 }, filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, filter: { borderWidth: 1, borderColor: colors.primary[300], padding: 9 }, selected: { backgroundColor: colors.teal[400], borderColor: colors.primary[800] }, filterText: { ...text.bodySm, color: colors.primary[800], textTransform: 'capitalize' }, row: { borderWidth: 1, borderColor: colors.primary[300], backgroundColor: colors.bg.white, padding: 14, flexDirection: 'row', gap: 12, alignItems: 'center' }, stationId: { ...text.headingSm, color: colors.primary[800] }, meta: { ...text.bodySm, color: colors.neutral[600], marginTop: 3 }, empty: { ...text.bodyMd, color: colors.neutral[600], marginTop: 24 }, pager: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 8 } });
