import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '../../src/components/ui/Button';
import { FloatingInput as Input } from '../../src/components/ui/Input';
import { InlineNotice } from '../../src/components/feedback/InlineNotice';
import { createAdminMmiApi } from '../../src/features/adminMmi/api';
import type { AdminMmiUsage } from '../../src/features/adminMmi/types';
import { navigateBackOr } from '../../src/lib/navigation';
import { supabase } from '../../src/lib/supabase';
import { colors, layout, text } from '../../src/theme';

const api = createAdminMmiApi(supabase);
export default function UsageScreen() {
  const [usage, setUsage] = useState<AdminMmiUsage | null>(null); const [loading, setLoading] = useState(true); const [userId, setUserId] = useState(''); const [provider, setProvider] = useState(''); const [model, setModel] = useState(''); const [stationId, setStationId] = useState(''); const [error, setError] = useState(false);
  const load = () => { setLoading(true); setError(false); void api.getUsage({ limit: 50, offset: 0, userId: userId || undefined, provider: provider || undefined, model: model || undefined, stationId: stationId || undefined }).then(setUsage).catch(() => setError(true)).finally(() => setLoading(false)); }; useEffect(load, []);
  return <SafeAreaView style={styles.safe}><View style={styles.header}><TouchableOpacity onPress={() => navigateBackOr(router, '/admin')} accessibilityRole="button"><Text style={styles.back}>Back to admin</Text></TouchableOpacity><Text style={styles.headerTitle}>USAGE AND COSTS</Text><View style={{ width: 104 }} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Usage and costs</Text><Text style={styles.sub}>Only provider-reported usage can be priced. Missing usage is labelled Cost unavailable, never zero.</Text>{error ? <InlineNotice title="Usage not loaded" message="Check filters and administrator access." tone="error" /> : null}<Input label="User ID" value={userId} onChangeText={setUserId} autoCapitalize="none" /><Input label="Provider" value={provider} onChangeText={setProvider} autoCapitalize="none" /><Input label="Model" value={model} onChangeText={setModel} autoCapitalize="none" /><Input label="Station ID" value={stationId} onChangeText={setStationId} autoCapitalize="none" /><Button label="Apply usage filters" onPress={load} small />{loading ? <ActivityIndicator color={colors.teal[400]} style={{ margin: 30 }} /> : usage ? <><View style={styles.summary}><Text style={styles.summaryText}>{usage.summary.callCount} calls · ${usage.summary.knownCost} known cost · {usage.summary.unknownCostCount} Cost unavailable · {usage.summary.averageLatencyMs}ms average</Text></View>{usage.rows.map((row) => <View key={row.usageId} style={styles.row}><Text style={styles.rowTitle}>{row.userDisplayName} · {row.stationId} · Question {row.promptOrder}</Text><Text style={styles.meta}>{row.provider} / {row.model} · {row.outcome} · {row.latencyMs}ms</Text><Text style={styles.meta}>{row.inputTokens ?? '—'} input · {row.outputTokens ?? '—'} output · {row.estimatedCost === null ? 'Cost unavailable' : `$${row.estimatedCost}`}</Text></View>)}</> : null}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg.primary }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 12, paddingHorizontal: layout.screenPaddingH, borderBottomWidth: 1, borderBottomColor: colors.primary[800] }, back: { ...text.labelMd, color: colors.primary[800], minWidth: 104 }, headerTitle: { ...text.labelMd, color: colors.primary[800] }, content: { padding: layout.screenPaddingH, paddingBottom: 48, gap: 10 }, title: { ...text.displayLg, color: colors.primary[800] }, sub: { ...text.bodyMd, color: colors.neutral[600], lineHeight: 22 }, summary: { backgroundColor: colors.teal[100], borderWidth: 1, borderColor: colors.teal[600], padding: 12 }, summaryText: { ...text.bodyMd, color: colors.primary[800] }, row: { backgroundColor: colors.bg.white, borderWidth: 1, borderColor: colors.primary[300], padding: 13 }, rowTitle: { ...text.headingSm, color: colors.primary[800] }, meta: { ...text.bodySm, color: colors.neutral[600], marginTop: 4 } });
